### ISSUE TITLE
undefined contacts

### ISSUE THREAD

**Issue by kromonos** [halcyon-suite/halcyon#10]
On some contacts I get "undefined" instead of her ID, when I want to reply to them.
On the screenshots trashserver@social.tchncs.de and thomas@metalhead.club
![halcyon_reply](https://user-images.githubusercontent.com/1553902/39322159-7785e148-4978-11e8-8a88-62e6708cbd0f.png)
![halcyon_reply_2](https://user-images.githubusercontent.com/1553902/39322161-77b7070a-4978-11e8-8eb1-12d3aae9a3bf.png)

**Comment by nipos** [comment]
Thank you very much for reporting that!
It doesn't happen that often so I forgot about it,sorry :(
I'll fix that with the release of version 1.0.3 (hopefully this weekend).
BTW the issue does not happen with some contacts but with some special circumstances.
When you reply to an original toot,it always works.
The problem is when you try to reply to an toot which has other answers below it.
I don't know why that happens yet but I think it should be easy to find out and fix.
