### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by vinzv** [halcyon-suite/halcyon#15]
If there was some i18n feature and strings gotten pulled out I'd volunteer on translating (at least to German).

**Comment by nipos** [comment]
Multiple languages have been on my todo list since I took over this project.
I need to change very many variables in order to support multiple languages as texts are currently directly written into the code.
I'm working on completely new settings right now for 1.2.0 and then I'll make some smaller bugfixes and small functions as patch releases to give the project a fast progress.
I don't want people to think it's dead again while I'm working on one big feature.
When I have much time again,1.3.0 will come with support for different languages but you should expect about 2 month for this to come.
German is my main language so translating to it wouldn't be an problem for me,too.
I can give you the initial language file so I can work on other things during this time but I think it's faster if I translate future updates with only a few additional strings myself.

**Comment by osapon** [comment]
In my repository, it corresponds to i18n.
https://github.com/osapon/halcyon
I prepared a German setting, but it has not been translated yet.
I'm accept either pull request or weblate.

**Comment by nipos** [comment]
As announced in our blog post,all Github issues are closed now!
We wrote all bugs to our to do list and will fix them in future releases without noting it here.
You can get new releases only from https://notabug.org/halcyon-suite/halcyon
Please do not open new issues here,use our new repository instead or write to us in the fediverse.
Our blog post: https://nikisoft.myblog.de/nikisoft/art/11626163/Our-move-from-Github-to-NotABug
