### ISSUE TITLE
'#' is not removed from search query

### ISSUE THREAD

**Issue by vanitasvitae** [halcyon-suite/halcyon#16]
Hi!
First of all, great project, thank you for that :heart:.

Now the problem:
If you enter a search query that already contains the leading '#' (eg. "#federated"), the search is executed for "##federated", which will give no results. I assume you forgot to sanitize the input there?

**Comment by nipos** [comment]
As Mastodon has no fulltext search by default,it always searches for hashtags.
Normally it's wanted to add an hashtag because you can only search for hashtags and users,not for normal words.
But you're right,if you already type an hashtag,it shouldn't add an second one.
I don't want to add even more work to the 1.2.0 release as my planned deadline is already over but I'll fix this in 1.2.1.

**Comment by nipos** [comment]
As announced in our blog post,all Github issues are closed now!
We wrote all bugs to our to do list and will fix them in future releases without noting it here.
You can get new releases only from https://notabug.org/halcyon-suite/halcyon
Please do not open new issues here,use our new repository instead or write to us in the fediverse.
Our blog post: https://nikisoft.myblog.de/nikisoft/art/11626163/Our-move-from-Github-to-NotABug
