### ISSUE TITLE
Doesn't load posts at end of page

### ISSUE THREAD

**Issue by ericblank** [halcyon-suite/halcyon#2]
The loading icon spins, but it never loads more posts

**Comment by nipos** [comment]
It works fine for me.
My current priority is working on bugs which always appear and on new features.
If you could open the Javascript console and give me the error messages,I could probably implement a small fix but right now I really don't have an idea where that problem could come from.
If you don't get an error message,I won't work on that problem now.

**Comment by ericblank** [comment]
I'll try it with a clean firefox profile

**Comment by ericblank** [comment]
Same result with firefox in safe mode. It works on Chrome.

Firefox Quantum 59.0.1 (64-bit) on Ubuntu 17.10

Console shows the following:

> TypeError: links.next is undefined[Learn More] halcyonUI.js:1199:38
> 	setTimeline/< https://social.dev-wiki.de/assets/js/halcyon/halcyonUI.js:1199:38
> 	dispatch https://yastatic.net/jquery/3.2.1/jquery.min.js:3:10264
> 	add/q.handle https://yastatic.net/jquery/3.2.1/jquery.min.js:3:8326

**Comment by Toromino** [comment]
Can confirm this issue on my end. Got the same problem with Firefox Quantum 59.0.1 and Tor Browser 7.5.2 (based on Mozilla Firefox 52.7.2) (32-bit). But it works fine in Chrome and Vivaldi.

**Comment by nipos** [comment]
I can confirm this issue now.
Normally I use Yandex Browser which is Chromium based and is seems to be fine in all Chromium based browsers so I didn't see the problem.
I just tried it in Firefox Quantum 57 and now it happens to me,too.
Yet I'm not absolutely sure what causes the problem but I'm working on a fix.

**Comment by nipos** [comment]
I identified and fixed that problem!
The problem was that Chromium displays HTTP headers in lower case while Firefox displays them in the original case and Halcyon used a case sensitive RegExp searching for a lower case word.
The RexExp is now case insensitive so it should work correctly in every browser.
That fixed it in my Firefox Quantum 57
Please note that the bugfix is not yet released and only available on my closed development server.
The fix will be distributed in the next update.
