### ISSUE TITLE
"Who to follow" weird suggestion

### ISSUE THREAD

**Issue by pinage404** [halcyon-suite/halcyon#24]
The "Who to follow" section propose to me people that i already followed

By the way, It's a good project =)

**Comment by neetshin** [comment]
Thanks for reporting and sorry for taking a lot of times.

In the next stable version, Halcyon will be switched to use [Vinayaka](https://github.com/distsn/vinayaka) which is an awesome project that provides recommended users from the fediverse.

Since Vinayaka does not need any authentication it can't detect whether you followed recommended users, so Halcyon still shows an account that you've already followed. So I refactored the interface:

<img width="301" alt="2018-01-28 14 28 43" src="https://user-images.githubusercontent.com/19276905/35480592-92a44036-0437-11e8-844f-6abc41b62b6d.png">

When you showed home page, Halcyon will fetch top 100 recommended users from Vinayaka and then cache them into your browser. if you've already followed some users, you can click × icon to exclude them from the list. This feature also will be included from the next stable version.

**Comment by nightpool** [comment]
Isn't who I follow public information though? Why would it need
authentication to determine that?

Second, is there a way to opt out of this for more privacy conscious users,
without sending your information to a third party?
