### ISSUE TITLE
'Other instances' link doesn't work

### ISSUE THREAD

**Issue by Toromino** [halcyon-suite/halcyon#3]
![image](https://user-images.githubusercontent.com/15093096/37876360-c561b3b2-303a-11e8-92e5-1d043a9e5caa.png)

Only a minor issue. But there's a link in the right menu saying 'Other instances', but it links to "http://instances.list" which doesn't exist. It seems to work in <1.0.0 Halcyon versions.

**Comment by nipos** [comment]
The older versions linked to an manually updated page.
I wanted to change that to the new instances list page which is also used by http://joinmastodon.org
Looks like I forgot that a .list top level domain doesn't even exist.
The correct domain is http://instances.social and that will be fixed in the next release.
