### ISSUE TITLE
Contact form broken

### ISSUE THREAD

**Issue by Aranad** [halcyon-suite/halcyon#5]
Hi there, I wanted to send a message to you asking for a little clarification about how to install Halcyon on my server (I installed it but don't understand how to create a accounts). But your contact form is broken, when I click submit it throws an error saying submit is undefined.

**Comment by nipos** [comment]
The form works fine for me,but I'll have a deeper look at it on Sunday.
But you don't have to wait that long,I can answer your question here.
You can't create accounts on Halcyon because it's only an client for Mastodon without an own server side implementation.
Register on any Mastodon instance listed at https://instances.social and login to Halcyon using @yourname@somemastodonserver.com
Most instances are for everyone and everything,but some are for special topics.
Your Mastodon instance is like an email provider - it's behind the @ of your address,but you can communicate with the whole network using it.
And Halcyon is for Mastodon what Outlook and Thunderbird are for emails - It offers you an simpler and more beautiful access to it.

**Comment by Aranad** [comment]
Oh right I see now, thanks a lot for the clear explanation :-)

**Comment by nipos** [comment]
My top priority was working on Halcyon instead of my private page so I didn't look at it again before today.
There was a small bug in the "if" statement on the server site so the form was always detected as invalid.
I fixed that now but I can't see the problem with the submit on the client side.
It's just an normal <button type="submit"> HTML element without any Javascript.
